-- Migration: 047_advance_settlements.sql
-- Enables settling invoices by deducting from existing advance balances.

BEGIN;

-- 1. Modify payment_type constraint to allow 'advance_settlement'
ALTER TABLE public.payment_vouchers DROP CONSTRAINT IF EXISTS payment_vouchers_payment_type_check;
ALTER TABLE public.payment_vouchers ADD CONSTRAINT payment_vouchers_payment_type_check 
  CHECK (payment_type IN ('regular', 'advance', 'advance_settlement'));

COMMENT ON COLUMN public.payment_vouchers.payment_type IS
  'v047: regular = سند صرف مرتبط بمستحقات | advance = دفعة مقدمة | advance_settlement = تسوية دفعة مقدمة مع فاتورة';

-- 2. Modify post_payment_voucher to ignore financial_transactions if it's an advance settlement
CREATE OR REPLACE FUNCTION public.post_payment_voucher(
    p_voucher_id UUID,
    p_user_id UUID
)
RETURNS VOID AS $$
DECLARE
    v_voucher RECORD;
    v_trans_type TEXT;
    v_alloc RECORD;
BEGIN
    SELECT * INTO v_voucher FROM public.payment_vouchers WHERE id = p_voucher_id FOR UPDATE;
    
    IF v_voucher IS NULL THEN
        RAISE EXCEPTION 'Voucher not found';
    END IF;

    IF v_voucher.status = 'posted' THEN
        RAISE EXCEPTION 'Voucher is already posted';
    END IF;

    -- Only check for financial_account_id if it's a regular or advance payment (not a settlement)
    IF v_voucher.payment_type IN ('regular', 'advance') AND v_voucher.financial_account_id IS NULL THEN
        RAISE EXCEPTION 'Cannot post a payment voucher without a financial account source unless it is an advance settlement';
    END IF;

    -- Create financial transaction ONLY if it's not a settlement
    IF v_voucher.payment_type IN ('regular', 'advance') THEN
        IF v_voucher.direction = 'outflow' THEN
            v_trans_type := 'withdrawal';
        ELSE
            v_trans_type := 'deposit';
        END IF;

        INSERT INTO public.financial_transactions (
            financial_account_id,
            transaction_date,
            transaction_type,
            amount,
            reference_type,
            reference_id,
            notes,
            created_by
        ) VALUES (
            v_voucher.financial_account_id,
            v_voucher.payment_date,
            v_trans_type,
            v_voucher.total_amount,
            'payment_voucher',
            p_voucher_id,
            'Auto-generated by Payment Voucher ' || v_voucher.voucher_no,
            p_user_id
        );
    END IF;

    -- Mark as posted
    UPDATE public.payment_vouchers 
    SET status = 'posted',
        posted_at = now(),
        posted_by = p_user_id,
        updated_at = now()
    WHERE id = p_voucher_id;

    -- Process allocations to update target invoice balances
    FOR v_alloc IN 
        SELECT pa.* FROM public.payment_allocations pa
        JOIN public.payment_voucher_parties pvp ON pvp.id = pa.payment_voucher_party_id
        WHERE pvp.payment_voucher_id = p_voucher_id
    LOOP
        IF v_alloc.source_entity_type = 'supplier_invoice' THEN
            UPDATE public.supplier_invoices 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                status = CASE WHEN paid_to_date + v_alloc.allocated_amount >= net_amount THEN 'paid' ELSE 'partially_paid' END
            WHERE id = v_alloc.source_entity_id;

        ELSIF v_alloc.source_entity_type = 'subcontractor_certificate' THEN
            UPDATE public.subcontractor_certificates 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                outstanding_amount = outstanding_amount - v_alloc.allocated_amount,
                status = CASE WHEN outstanding_amount - v_alloc.allocated_amount <= 0 THEN 'paid' ELSE 'partially_paid' END
            WHERE id = v_alloc.source_entity_id;

        ELSIF v_alloc.source_entity_type = 'company_purchase_invoice' THEN
            UPDATE public.company_purchase_invoices 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                outstanding_amount = outstanding_amount - v_alloc.allocated_amount,
                status = CASE WHEN outstanding_amount - v_alloc.allocated_amount <= 0 THEN 'paid' ELSE 'partially_paid' END,
                updated_at = now()
            WHERE id = v_alloc.source_entity_id;
        END IF;
    END LOOP;

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Create a function to safely deduct from total_advanced (increasing total_deducted)
CREATE OR REPLACE FUNCTION public.deduct_party_advance_balance(
  p_company_id uuid,
  p_project_id uuid, -- Can be NULL for company-level advances
  p_party_id uuid,
  p_party_type text,
  p_deduct_amount numeric
) RETURNS void AS $$
DECLARE
  v_balance numeric;
BEGIN
  -- Validate inputs
  IF p_deduct_amount <= 0 THEN
      RAISE EXCEPTION 'Deduction amount must be strictly positive';
  END IF;

  -- Lock the row and fetch current remaining balance
  SELECT balance_remaining INTO v_balance
  FROM public.party_advance_balances
  WHERE company_id = p_company_id
    AND party_id = p_party_id
    AND party_type = p_party_type
    AND (project_id = p_project_id OR (project_id IS NULL AND p_project_id IS NULL))
  FOR UPDATE;

  IF v_balance IS NULL THEN
      RAISE EXCEPTION 'Advance balance not found for this party/project combination';
  END IF;

  IF v_balance < p_deduct_amount THEN
      RAISE EXCEPTION 'Insufficient advance balance. Requested: %, Available: %', p_deduct_amount, v_balance;
  END IF;

  -- Update deduction
  UPDATE public.party_advance_balances
  SET total_deducted = total_deducted + p_deduct_amount,
      updated_at = now()
  WHERE company_id = p_company_id
    AND party_id = p_party_id
    AND party_type = p_party_type
    AND (project_id = p_project_id OR (project_id IS NULL AND p_project_id IS NULL));

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION public.deduct_party_advance_balance IS
  'v047: Safely deducts from a party''s advance balance while preventing negative remaining balance.';

COMMIT;
