-- Migration: 049_fix_supplier_invoice_payment.sql
-- Fixes missing outstanding_amount deductions for supplier_invoices in payment logic.

BEGIN;

CREATE OR REPLACE FUNCTION public.check_and_update_allocation_balance()
RETURNS TRIGGER AS $$
DECLARE
    v_outstanding NUMERIC(18,2);
    v_status TEXT;
    v_voucher_status TEXT;
BEGIN
    SELECT pv.status INTO v_voucher_status
    FROM public.payment_vouchers pv
    JOIN public.payment_voucher_parties pvp ON pvp.id = NEW.payment_voucher_party_id
    WHERE pv.id = pvp.payment_voucher_id;

    IF v_voucher_status != 'posted' THEN
        RETURN NEW;
    END IF;

    IF NEW.source_entity_type = 'supplier_invoice' THEN
        SELECT (net_amount - paid_to_date), status INTO v_outstanding, v_status
        FROM public.supplier_invoices WHERE id = NEW.source_entity_id FOR UPDATE;

        IF NEW.allocated_amount > v_outstanding THEN
            RAISE EXCEPTION 'Allocation limit exceeded: Target supplier invoice has only % outstanding.', v_outstanding;
        END IF;

        UPDATE public.supplier_invoices 
        SET paid_to_date = paid_to_date + NEW.allocated_amount,
            outstanding_amount = outstanding_amount - NEW.allocated_amount,
            status = CASE WHEN paid_to_date + NEW.allocated_amount >= net_amount THEN 'paid' ELSE 'partially_paid' END
        WHERE id = NEW.source_entity_id;

    ELSIF NEW.source_entity_type = 'subcontractor_certificate' THEN
        SELECT outstanding_amount, status INTO v_outstanding, v_status
        FROM public.subcontractor_certificates WHERE id = NEW.source_entity_id FOR UPDATE;

        IF NEW.allocated_amount > v_outstanding THEN
            RAISE EXCEPTION 'Allocation limit exceeded: Target subcontractor certificate has only % outstanding.', v_outstanding;
        END IF;

        UPDATE public.subcontractor_certificates 
        SET paid_to_date = paid_to_date + NEW.allocated_amount,
            outstanding_amount = outstanding_amount - NEW.allocated_amount,
            status = CASE WHEN outstanding_amount - NEW.allocated_amount <= 0 THEN 'paid' ELSE 'partially_paid' END
        WHERE id = NEW.source_entity_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


CREATE OR REPLACE FUNCTION public.post_payment_voucher(
    p_voucher_id UUID,
    p_user_id UUID
)
RETURNS VOID AS $$
DECLARE
    v_voucher RECORD;
    v_trans_type TEXT;
    v_alloc RECORD;
BEGIN
    SELECT * INTO v_voucher FROM public.payment_vouchers WHERE id = p_voucher_id FOR UPDATE;
    
    IF v_voucher IS NULL THEN
        RAISE EXCEPTION 'Voucher not found';
    END IF;

    IF v_voucher.status = 'posted' THEN
        RAISE EXCEPTION 'Voucher is already posted';
    END IF;

    IF v_voucher.payment_type IN ('regular', 'advance') AND v_voucher.financial_account_id IS NULL THEN
        RAISE EXCEPTION 'Cannot post a payment voucher without a financial account source unless it is an advance settlement';
    END IF;

    IF v_voucher.direction = 'outflow' THEN
        v_trans_type := 'withdrawal';
    ELSE
        v_trans_type := 'deposit';
    END IF;

    -- Only insert financial_transactions if it's NOT an advance_settlement
    IF v_voucher.payment_type IN ('regular', 'advance') THEN
        INSERT INTO public.financial_transactions (
            financial_account_id,
            transaction_date,
            transaction_type,
            amount,
            reference_type,
            reference_id,
            notes,
            created_by
        ) VALUES (
            v_voucher.financial_account_id,
            v_voucher.payment_date,
            v_trans_type,
            v_voucher.total_amount,
            'payment_voucher',
            p_voucher_id,
            'Auto-generated by Payment Voucher ' || v_voucher.voucher_no,
            p_user_id
        );
    END IF;

    UPDATE public.payment_vouchers 
    SET status = 'posted',
        posted_at = now(),
        posted_by = p_user_id,
        updated_at = now()
    WHERE id = p_voucher_id;

    FOR v_alloc IN 
        SELECT pa.* FROM public.payment_allocations pa
        JOIN public.payment_voucher_parties pvp ON pvp.id = pa.payment_voucher_party_id
        WHERE pvp.payment_voucher_id = p_voucher_id
    LOOP
        IF v_alloc.source_entity_type = 'supplier_invoice' THEN
            UPDATE public.supplier_invoices 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                outstanding_amount = outstanding_amount - v_alloc.allocated_amount,
                status = CASE WHEN paid_to_date + v_alloc.allocated_amount >= net_amount THEN 'paid' ELSE 'partially_paid' END,
                updated_at = now()
            WHERE id = v_alloc.source_entity_id;

        ELSIF v_alloc.source_entity_type = 'subcontractor_certificate' THEN
            UPDATE public.subcontractor_certificates 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                outstanding_amount = outstanding_amount - v_alloc.allocated_amount,
                status = CASE WHEN outstanding_amount - v_alloc.allocated_amount <= 0 THEN 'paid' ELSE 'partially_paid' END,
                updated_at = now()
            WHERE id = v_alloc.source_entity_id;

        ELSIF v_alloc.source_entity_type = 'company_purchase_invoice' THEN
            UPDATE public.company_purchase_invoices 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                outstanding_amount = outstanding_amount - v_alloc.allocated_amount,
                status = CASE WHEN outstanding_amount - v_alloc.allocated_amount <= 0 THEN 'paid' ELSE 'partially_paid' END,
                updated_at = now()
            WHERE id = v_alloc.source_entity_id;
        END IF;
    END LOOP;

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Fix any old supplier invoices that might have been out of sync due to the bug
UPDATE public.supplier_invoices
SET outstanding_amount = net_amount - paid_to_date - COALESCE(returned_amount, 0)
WHERE outstanding_amount != net_amount - paid_to_date - COALESCE(returned_amount, 0);

COMMIT;
