-- Migration 057: Financial Transactions Enrichment
-- Add project_id and attachment_urls to financial_transactions

ALTER TABLE public.financial_transactions
  ADD COLUMN IF NOT EXISTS project_id UUID REFERENCES public.projects(id),
  ADD COLUMN IF NOT EXISTS attachment_urls TEXT[] DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_fin_tx_project ON public.financial_transactions(project_id);

-- Update existing transactions to inherit project_id from their accounts (if it's a project account)
UPDATE public.financial_transactions ft
SET project_id = fa.project_id
FROM public.financial_accounts fa
WHERE ft.financial_account_id = fa.id
  AND fa.project_id IS NOT NULL
  AND ft.project_id IS NULL;

-- Update existing transactions to inherit project_id from reference_types where applicable (like payment_voucher)
UPDATE public.financial_transactions ft
SET project_id = pv.project_id
FROM public.payment_vouchers pv
WHERE ft.reference_type = 'payment_voucher' 
  AND ft.reference_id = pv.id
  AND ft.project_id IS NULL;

-- Also update existing owner_collections reference_type
UPDATE public.financial_transactions ft
SET project_id = oc.project_id
FROM public.owner_collections oc
WHERE ft.reference_type = 'owner_collection' 
  AND ft.reference_id = oc.id
  AND ft.project_id IS NULL;

-- Also update post_payment_voucher to inject project_id
CREATE OR REPLACE FUNCTION public.post_payment_voucher(
    p_voucher_id UUID,
    p_user_id UUID
)
RETURNS VOID AS $$
DECLARE
    v_voucher RECORD;
    v_trans_type TEXT;
    v_alloc RECORD;
BEGIN
    SELECT * INTO v_voucher FROM public.payment_vouchers WHERE id = p_voucher_id FOR UPDATE;
    
    IF v_voucher IS NULL THEN
        RAISE EXCEPTION 'Voucher not found';
    END IF;

    IF v_voucher.status = 'posted' THEN
        RAISE EXCEPTION 'Voucher is already posted';
    END IF;

    IF v_voucher.financial_account_id IS NULL THEN
        RAISE EXCEPTION 'Cannot post a payment voucher without a financial account source';
    END IF;

    IF v_voucher.direction = 'outflow' THEN
        v_trans_type := 'withdrawal';
    ELSE
        v_trans_type := 'deposit';
    END IF;

    INSERT INTO public.financial_transactions (
        financial_account_id,
        transaction_date,
        transaction_type,
        amount,
        reference_type,
        reference_id,
        notes,
        created_by,
        project_id
    ) VALUES (
        v_voucher.financial_account_id,
        v_voucher.payment_date,
        v_trans_type,
        v_voucher.total_amount,
        'payment_voucher',
        p_voucher_id,
        'Auto-generated by Payment Voucher ' || v_voucher.voucher_no,
        p_user_id,
        v_voucher.project_id
    );

    UPDATE public.payment_vouchers 
    SET status = 'posted',
        posted_at = now(),
        posted_by = p_user_id,
        updated_at = now()
    WHERE id = p_voucher_id;

    FOR v_alloc IN 
        SELECT pa.* FROM public.payment_allocations pa
        JOIN public.payment_voucher_parties pvp ON pvp.id = pa.payment_voucher_party_id
        WHERE pvp.payment_voucher_id = p_voucher_id
    LOOP
        IF v_alloc.source_entity_type = 'supplier_invoice' THEN
            UPDATE public.supplier_invoices 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                status = CASE WHEN paid_to_date + v_alloc.allocated_amount >= net_amount THEN 'paid' ELSE 'partially_paid' END
            WHERE id = v_alloc.source_entity_id;
        ELSIF v_alloc.source_entity_type = 'subcontractor_certificate' THEN
            UPDATE public.subcontractor_certificates 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                outstanding_amount = outstanding_amount - v_alloc.allocated_amount,
                status = CASE WHEN outstanding_amount - v_alloc.allocated_amount <= 0 THEN 'paid' ELSE 'partially_paid' END
            WHERE id = v_alloc.source_entity_id;
        END IF;
    END LOOP;

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
