-- Migration 058: Add counterpart name to financial transactions

ALTER TABLE public.financial_transactions
  ADD COLUMN IF NOT EXISTS counterpart_name TEXT;

-- Update the Payment Voucher Posting RPC to aggregate party names
CREATE OR REPLACE FUNCTION public.post_payment_voucher(
    p_voucher_id UUID,
    p_user_id UUID
)
RETURNS VOID AS $$
DECLARE
    v_voucher RECORD;
    v_trans_type TEXT;
    v_alloc RECORD;
    v_party_names TEXT;
BEGIN
    SELECT * INTO v_voucher FROM public.payment_vouchers WHERE id = p_voucher_id FOR UPDATE;
    
    IF v_voucher IS NULL THEN
        RAISE EXCEPTION 'Voucher not found';
    END IF;

    IF v_voucher.status = 'posted' THEN
        RAISE EXCEPTION 'Voucher is already posted';
    END IF;

    IF v_voucher.financial_account_id IS NULL THEN
        RAISE EXCEPTION 'Cannot post a payment voucher without a financial account source';
    END IF;

    IF v_voucher.direction = 'outflow' THEN
        v_trans_type := 'withdrawal';
    ELSE
        v_trans_type := 'deposit';
    END IF;

    -- Aggregate party names for counterpart_name
    SELECT string_agg(p.arabic_name, '، ') INTO v_party_names
    FROM public.payment_voucher_parties pvp
    JOIN public.parties p ON p.id = pvp.party_id
    WHERE pvp.payment_voucher_id = p_voucher_id;

    INSERT INTO public.financial_transactions (
        financial_account_id,
        transaction_date,
        transaction_type,
        amount,
        reference_type,
        reference_id,
        notes,
        created_by,
        project_id,
        counterpart_name
    ) VALUES (
        v_voucher.financial_account_id,
        v_voucher.payment_date,
        v_trans_type,
        v_voucher.total_amount,
        'payment_voucher',
        p_voucher_id,
        'Auto-generated by Payment Voucher ' || v_voucher.voucher_no,
        p_user_id,
        v_voucher.project_id,
        COALESCE(v_party_names, 'مستفيد غير مسجل')
    );

    UPDATE public.payment_vouchers 
    SET status = 'posted',
        posted_at = now(),
        posted_by = p_user_id,
        updated_at = now()
    WHERE id = p_voucher_id;

    FOR v_alloc IN 
        SELECT pa.* FROM public.payment_allocations pa
        JOIN public.payment_voucher_parties pvp ON pvp.id = pa.payment_voucher_party_id
        WHERE pvp.payment_voucher_id = p_voucher_id
    LOOP
        IF v_alloc.source_entity_type = 'supplier_invoice' THEN
            UPDATE public.supplier_invoices 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                status = CASE WHEN paid_to_date + v_alloc.allocated_amount >= net_amount THEN 'paid' ELSE 'partially_paid' END
            WHERE id = v_alloc.source_entity_id;
        ELSIF v_alloc.source_entity_type = 'subcontractor_certificate' THEN
            UPDATE public.subcontractor_certificates 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                outstanding_amount = outstanding_amount - v_alloc.allocated_amount,
                status = CASE WHEN outstanding_amount - v_alloc.allocated_amount <= 0 THEN 'paid' ELSE 'partially_paid' END
            WHERE id = v_alloc.source_entity_id;
        END IF;
    END LOOP;

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==========================================
-- DATA MIGRATION: Backfill counterpart_name for old transactions
-- ==========================================

-- 1. Owner Collections & Advances
UPDATE public.financial_transactions ft
SET counterpart_name = 'المالك: ' || p.arabic_name
FROM public.owner_collections oc
JOIN public.parties p ON p.id = oc.owner_party_id
WHERE ft.reference_type IN ('owner_collection', 'owner_advance')
  AND ft.reference_id = oc.id
  AND ft.counterpart_name IS NULL;

-- 2. Payment Vouchers
UPDATE public.financial_transactions ft
SET counterpart_name = COALESCE(
  (
    SELECT string_agg(p.arabic_name, '، ')
    FROM public.payment_voucher_parties pvp
    JOIN public.parties p ON p.id = pvp.party_id
    WHERE pvp.payment_voucher_id = ft.reference_id
  ),
  'مستفيد (من الفاتورة)'
)
WHERE ft.reference_type = 'payment_voucher'
  AND ft.counterpart_name IS NULL;

-- 3. Transfers / Manual Adjustments (best effort, no direct foreign keys for counterpart name historically in all cases)
-- Note: historically transfer_in/transfer_out reference_id was missing or inconsistent, so we leave them empty or let the user fix them if needed. 
