-- Migration 063: Fix post_payment_voucher regression
-- This restores the certificate_status enum cast and company_purchase_invoice handling
-- which were accidentally removed in migration 058.

CREATE OR REPLACE FUNCTION public.post_payment_voucher(
    p_voucher_id UUID,
    p_user_id UUID
)
RETURNS VOID AS $$
DECLARE
    v_voucher RECORD;
    v_trans_type TEXT;
    v_alloc RECORD;
    v_party_names TEXT;
BEGIN
    SELECT * INTO v_voucher FROM public.payment_vouchers WHERE id = p_voucher_id FOR UPDATE;
    
    IF v_voucher IS NULL THEN
        RAISE EXCEPTION 'Voucher not found';
    END IF;

    IF v_voucher.status = 'posted' THEN
        RAISE EXCEPTION 'Voucher is already posted';
    END IF;

    IF v_voucher.financial_account_id IS NULL THEN
        RAISE EXCEPTION 'Cannot post a payment voucher without a financial account source';
    END IF;

    IF v_voucher.direction = 'outflow' THEN
        v_trans_type := 'withdrawal';
    ELSE
        v_trans_type := 'deposit';
    END IF;

    -- Aggregate party names for counterpart_name
    SELECT string_agg(p.arabic_name, '، ') INTO v_party_names
    FROM public.payment_voucher_parties pvp
    JOIN public.parties p ON p.id = pvp.party_id
    WHERE pvp.payment_voucher_id = p_voucher_id;

    -- Register the financial transaction (treasury deduction/addition)
    INSERT INTO public.financial_transactions (
        financial_account_id,
        transaction_date,
        transaction_type,
        amount,
        reference_type,
        reference_id,
        notes,
        created_by,
        project_id,
        counterpart_name
    ) VALUES (
        v_voucher.financial_account_id,
        v_voucher.payment_date,
        v_trans_type,
        v_voucher.total_amount,
        'payment_voucher',
        p_voucher_id,
        'Auto-generated by Payment Voucher ' || v_voucher.voucher_no,
        p_user_id,
        v_voucher.project_id,
        COALESCE(v_party_names, 'مستفيد غير مسجل')
    );

    -- Mark the voucher as posted
    UPDATE public.payment_vouchers 
    SET status = 'posted',
        posted_at = now(),
        posted_by = p_user_id,
        updated_at = now()
    WHERE id = p_voucher_id;

    -- Settle all draft allocations now that the voucher is posted
    FOR v_alloc IN 
        SELECT pa.* FROM public.payment_allocations pa
        JOIN public.payment_voucher_parties pvp ON pvp.id = pa.payment_voucher_party_id
        WHERE pvp.payment_voucher_id = p_voucher_id
    LOOP
        IF v_alloc.source_entity_type = 'supplier_invoice' THEN
            UPDATE public.supplier_invoices 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                status = CASE WHEN paid_to_date + v_alloc.allocated_amount >= net_amount THEN 'paid' ELSE 'partially_paid' END
            WHERE id = v_alloc.source_entity_id;

        ELSIF v_alloc.source_entity_type = 'subcontractor_certificate' THEN
            -- certificate_status ENUM: 'approved' for partial, 'paid_in_full' when done
            UPDATE public.subcontractor_certificates 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                outstanding_amount = outstanding_amount - v_alloc.allocated_amount,
                status = CASE
                    WHEN outstanding_amount - v_alloc.allocated_amount <= 0 THEN 'paid_in_full'::public.certificate_status
                    ELSE 'approved'::public.certificate_status
                END
            WHERE id = v_alloc.source_entity_id;

        ELSIF v_alloc.source_entity_type = 'company_purchase_invoice' THEN
            UPDATE public.company_purchase_invoices 
            SET paid_to_date = paid_to_date + v_alloc.allocated_amount,
                outstanding_amount = outstanding_amount - v_alloc.allocated_amount,
                status = CASE WHEN outstanding_amount - v_alloc.allocated_amount <= 0 THEN 'paid' ELSE 'partially_paid' END,
                updated_at = now()
            WHERE id = v_alloc.source_entity_id;

        END IF;
    END LOOP;

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
